import type { Metadata } from "next";
import {Quicksand}  from "next/font/google"
import {RootProviders} from "@/providers/RootProviders";
import "./globals.css";

const quicksand = Quicksand({subsets: ["latin"], variable: "--font-quicksand"})

export const metadata: Metadata = {
  title: {
      template: "%s | PaxDigital",
      default: "PaxDigital"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className} antialiased`}
      >

      <main className="w-full min-h-dvh">
          <RootProviders>
              {children}
          </RootProviders>
      </main>
      </body>
    </html>
  );
}
